{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "oauth2-server.fullname" . }}
  labels:
    {{- include "oauth2-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "oauth2-server.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- else }}
  ingress:
  - from: []
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- else }}
  egress:
  - to: []
  {{- end }}
{{- end }}