{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-server.fullname" . }}
  labels:
    {{- include "oauth2-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.jwtSecretKey }}: {{ .Values.config.jwtSecret | b64enc | quote }}
  {{ .Values.secrets.clientSecretKey }}: {{ .Values.config.oauth2.clientSecret | b64enc | quote }}
  mongo-uri: {{ include "oauth2-server.mongodbUri" . | b64enc | quote }}
{{- end }}
---
{{- if and (not .Values.secrets.socialSecrets.existingSecret) (or .Values.config.socialLogin.google.clientSecret .Values.config.socialLogin.github.clientSecret .Values.config.socialLogin.facebook.clientSecret .Values.config.socialLogin.apple.clientSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oauth2-server.fullname" . }}-social
  labels:
    {{- include "oauth2-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.config.socialLogin.google.clientSecret }}
  {{ .Values.secrets.socialSecrets.googleClientSecretKey }}: {{ .Values.config.socialLogin.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.socialLogin.github.clientSecret }}
  {{ .Values.secrets.socialSecrets.githubClientSecretKey }}: {{ .Values.config.socialLogin.github.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.socialLogin.facebook.clientSecret }}
  {{ .Values.secrets.socialSecrets.facebookClientSecretKey }}: {{ .Values.config.socialLogin.facebook.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.config.socialLogin.apple.clientSecret }}
  {{ .Values.secrets.socialSecrets.appleClientSecretKey }}: {{ .Values.config.socialLogin.apple.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}